#1
#Running a command
#FROM debian:8
#CMD ["echo", "Hello from Jeetu@Debian"]

#2
#Hosting a website
FROM nginx:1.15
COPY index.html /usr/share/nginx/html

#3
#Sharing files from volume, between two containers
